/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "aesd-circular-buffer.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_sane(void);
extern void test_init(void);
extern void test_add_entry(void);
extern void test_aesd_circular_buffer_find_entry_offset_for_fpos(void);
extern void test_circular_buffer(void);
extern void test_circular_buffer_assignment7(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, int line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/aesd-circular-buffer_test.c");
  run_test(test_sane, "test_sane", 10);
  run_test(test_init, "test_init", 60);
  run_test(test_add_entry, "test_add_entry", 80);
  run_test(test_aesd_circular_buffer_find_entry_offset_for_fpos, "test_aesd_circular_buffer_find_entry_offset_for_fpos", 114);
  run_test(test_circular_buffer, "test_circular_buffer", 197);
  run_test(test_circular_buffer_assignment7, "test_circular_buffer_assignment7", 243);

  return UnityEnd();
}
